In [ ]:
'''
GRUP 6 - TCI
1497657 - Braian Maldonado Arce
1532569 - Lluis Garcia Monreal
'''

In [1]:
import sys
import os
import numpy as np

from codingTools import *

In [2]:

# PARA BITPACKING !!!!
######LOAD RAW IMAGE###### 
#dtype --> > stands for big endian, i stands for integer, 2 stands for 2 bytes

#funciona
originalFile="../images/n1_GRAY.1_2560_2048_1_0_8_0_0_0.raw" #uint8
ImageRaw = load_image_raw(originalFile, 1, 2560, 2048, "uint8") #https://numpy.org/doc/stable/reference/arrays.dtypes.html
original_image = ImageRaw.load_image_raw()
##############################

In [3]:
# BITPACKING EXECUTION
BP = BitPacking("../images/n1_GRAY.1_2560_2048_1_0_8_0_0_0BITPACKING.raw",original_image)
BP.coding()
imagenResultado = BP.decoding()

#print(original_image == imagenResultado)

open ok
open ok
[[[ True  True  True ...  True  True  True]
  [ True  True  True ...  True  True  True]
  [ True  True  True ...  True  True  True]
  ...
  [ True  True  True ...  True  True  True]
  [ True  True  True ...  True  True  True]
  [ True  True  True ...  True  True  True]]]


In [ ]:
#Elegir imagen para aplicar todas las funcionalidades:

In [2]:
######LOAD RAW IMAGE######
#dtype --> > stands for big endian, i stands for integer, 2 stands for 2 bytes
#originalFile="../images/03508649.1_512_512_2_0_12_0_0_0.raw" #int16
#originalFile="../images/n1_GRAY.1_2560_2048_1_0_8_0_0_0.raw" #uint8
#originalFile="../images/03508649.1_128_128_1_0_8_0_0_0.raw"
#ImageRaw = load_image_raw(originalFile, 1, 128, 128, "uint8")
originalFile = "../images/03508649.1_512_512_2_0_12_0_0_0d.raw"
ImageRaw = load_image_raw(originalFile, 1, 512, 512, ">i2") #https://numpy.org/doc/stable/reference/arrays.dtypes.html
original_image = ImageRaw.load_image_raw()
##############################

In [4]:
########STATISTICS##########
statisticsINICI = statistics(original_image)
entropyINICI = statisticsINICI.compute_entropy()
print("order zero entropy of the image:", entropyINICI)

print('Max value:', statisticsINICI.max_value)
print('Min value:', statisticsINICI.min_value)
print('Dynamic range:', statisticsINICI.dynamic_range)




order zero entropy of the image: 10.431490855522489
Max value: 3438
Min value: 181
Dynamic range: 3257


In [5]:
#WAVELET FUNCION FORWARD y INREVERSE

image_data_empty = ImageRaw.get_image_structure_empty()

print('original imagen \n',original_image)

wav = Wavelet(original_image,3)

matriz_wavelet = wav.forward(image_data_empty)

print('matriz forward Wavelet\n',matriz_wavelet)

matriz_recuperada = wav.inverse(matriz_wavelet,image_data_empty)

print('matriz inverse wavelet \n',matriz_recuperada)



original imagen 
 [[[356 359 386 ... 415 398 389]
  [351 362 363 ... 417 405 398]
  [355 363 394 ... 419 398 414]
  ...
  [361 375 414 ... 436 417 414]
  [331 341 374 ... 442 380 406]
  [332 344 354 ... 406 398 368]]]
(1, 512, 512)
dim: 1
fil: 512
col 512
dim: 1
fil: 256
col 256
dim: 1
fil: 128
col 128
matriz forward Wavelet
 [[[439. 555. 644. ...   2.   9.   9.]
  [527. 669. 786. ...  21.  27.   7.]
  [617. 787. 922. ...  11.  11. -16.]
  ...
  [ 51.  -6.  22. ...  21.   4.   3.]
  [ 10.   5.  -8. ...   6. -16. -26.]
  [ -2.  11. -14. ... -25.  -8.  30.]]]
matriz inverse wavelet 
 [[[356. 359. 386. ... 415. 398. 389.]
  [351. 362. 363. ... 417. 405. 398.]
  [355. 363. 394. ... 419. 398. 414.]
  ...
  [361. 375. 414. ... 436. 417. 414.]
  [331. 341. 374. ... 442. 380. 406.]
  [332. 344. 354. ... 406. 398. 368.]]]


In [3]:
# PREDICCION Y CUANTIFICACIÓN para ver el mejor predictor 
image_data_empty = ImageRaw.get_image_structure_empty()
pred1 = Prediction(original_image)
imagen_prima1 = pred1.north_and_east(image_data_empty)
residu1 = original_image-imagen_prima1
print(residu1)

q = Quantizer(1,10)
image_quantized = ImageRaw.get_image_structure_empty()
q.quantize(residu1,image_quantized)# image quantized = r prima !!hem de treballar amb aquesta

image_DEquantized = ImageRaw.get_image_structure_empty()
q.dequantize(image_quantized,image_DEquantized) # image desquantized = r barret

aux_image = image_DEquantized + imagen_prima1  # utilitzar rprima en el predictor 

print(aux_image)


m = Metrics(original_image,aux_image)
m.compute()



[[[  0.   0.   0. ...   0.   0.   0.]
  [  0.   0.   0. ...   0.   0.   0.]
  [  0.   0. 364. ... 432. 415. 403.]
  ...
  [  0.   0. 377. ... 452. 438. 429.]
  [  0.   0. 363. ... 442. 431. 415.]
  [  0.   0. 359. ... 431. 409. 406.]]]
[[[356. 359. 386. ... 415. 398. 389.]
  [351. 362. 363. ... 417. 405. 398.]
  [355. 363. 390. ... 417. 393. 411.]
  ...
  [361. 375. 407. ... 434. 409. 405.]
  [331. 341. 371. ... 440. 379. 401.]
  [332. 344. 345. ... 405. 389. 362.]]]
bits 12
MSE= 28.3375244140625
PSNR= 57.72145904893747
PAE= 9.0


In [4]:
#RESULTADOS PREDICTOR
statistics1 = statistics(original_image)
entropy1 = statistics1.compute_entropy()
print("Entropia imagen original:", entropy1)

statistics4 = statistics(residu1)
entropy4 = statistics4.compute_entropy()
print("Entropia predictor north and east (residu):", entropy4)

statistics5 = statistics(image_quantized)
entropy5 = statistics5.compute_entropy()
print("Entropia predictor north and east (quantizado):", entropy5)


Entropia imagen original: 10.431490855522489
Entropia predictor north and east (residu): 10.369048363504998
Entropia predictor north and east (quantizado): 7.081423063889048


In [5]:
#PREDICTOR + CUANTIZADOR FINAL (ultimas 2 sesiones)
image_data_empty = ImageRaw.get_image_structure_empty()
q=Quantizer(1,10)
        
dimension = image_data_empty.shape[0]
filas = image_data_empty.shape[1]
columnas = image_data_empty.shape[2]
#result = np.copy(empty_image)
        
p=ImageRaw.get_image_structure_empty()
x_barret=ImageRaw.get_image_structure_empty()
#r = ImageRaw.get_image_structure_empty()
r_prima = 0#ImageRaw.get_image_structure_empty()
r_2prima = 0#ImageRaw.get_image_structure_empty()
        
for dim in range(dimension):
    for i in range(filas):
        for j in range(columnas):     
            if j==0:
                p[dim][i][j]=0
                #r[dim][i][j]=
                r = original_image[dim][i][j] - p[dim][i][j] #codigo profe
                r_prima= r//10 
                #q.quantize(r,r_prima)
                r_2prima = r_prima*10
                #q.dequantize(r_prima,r_2prima)
                x_barret[dim][i][j] =  p[dim][i][j] + r_2prima #[dim][i][j]  #codigo profe
                
            else:  
                #codigo nuestro
                #p[dim][i][j]=p[dim][i][j-1]+img_desq[dim][i][j]
                
                p[dim][i][j] = original_image[dim][i][j-1] #codigo profe
                #r[dim][i][j]
                r = original_image[dim][i][j] - p[dim][i][j] #codigo profe
                r_prima= r//10
                #q.quantize(r,r_prima)
                r_2prima = r_prima*10
                #q.dequantize(r_prima,r_2prima)
                x_barret[dim][i][j] =  p[dim][i][j] + r_2prima #[dim][i][j]  #codigo profe
        


In [6]:
#RESULTADOS 
image_data_empty = ImageRaw.get_image_structure_empty()
pred1 = Prediction(x_barret)
imagen_prima1 = pred1.north_and_east(image_data_empty)
residu1 = original_image-imagen_prima1
    
q=Quantizer(1,10)
img_q=ImageRaw.get_image_structure_empty()
q.quantize(residu1, img_q)
        
img_desq=ImageRaw.get_image_structure_empty()
q.dequantize(img_q, img_desq)
        
aux_img=img_desq+imagen_prima1
m=Metrics(original_image, aux_img)
m.compute()

bits 12
MSE= 28.512107849121094
PSNR= 57.69478487082531
PAE= 9.0
