In [1]:
import sys
import os
import numpy as np

from codingTools import *

In [2]:
######LOAD RAW IMAGE######
#dtype --> > stands for big endian, i stands for integer, 2 stands for 2 bytes
#originalFile="../images/03508649.1_512_512_2_0_12_0_0_0.raw" #int16
#originalFile="../images/n1_GRAY.1_2560_2048_1_0_8_0_0_0.raw" #uint8
originalFile="../images/03508649.1_128_128_1_0_8_0_0_0.raw"
ImageRaw = load_image_raw(originalFile, 1, 128, 128, "uint8")
#originalFile = "../images/03508649.1_512_512_2_0_12_0_0_0d.raw"
#ImageRaw = load_image_raw(originalFile, 1, 512, 512, ">i2") #https://numpy.org/doc/stable/reference/arrays.dtypes.html
original_image = ImageRaw.load_image_raw()
##############################

In [3]:
########STATISTICS##########
statistics = statistics(original_image)
entropy = statistics.compute_entropy()
print("order zero entropy of the image:", entropy)

print('Max value:', statistics.max_value)
print('Min value:', statistics.min_value)
print('Dynamic range:', statistics.dynamic_range)




order zero entropy of the image: 6.7004541529645625
Max value: 251
Min value: 5
Dynamic range: 246


In [4]:
## input bitstream ##
inputbit = binary_file_input('bitpacket.txt')
inputbit.open_binay_file_input()

inputbit.read_value(10)


open ok


3

In [9]:
## output bitstream ##
outputbit = binary_file_output('test.txt')

value = 999999999
nBits = utils.needed_bits(value)
print('num of bits:', nBits)

outputbit.open_binay_file_output()
outputbit.write_value(value, nBits)
outputbit.close_binary_file_output()

print('size file:',outputbit.size_of_file())

num of bits: 30
open ok
size file: 4


In [2]:
lista_tridimensional = [
    [
        [7, 12, 8, 10, 6, 4, 34, 68],
        [21, 33, 5, 1, 6, 9, 77, 88],
        [15, 10, 9, 4, 65, 98, 45, 16],
        [11, 19, 27, 29, 44, 37, 66, 52],
        [122, 146, 173, 200, 206, 201, 188, 197],
        [101, 108, 100, 164, 222, 178, 210, 225],
        [50, 30, 20, 5, 199, 240, 202, 190],
        [15, 25, 2, 10, 100, 45, 21, 2],
    ]
]

# Convertir a NumPy array
imagen_prueba = np.array(lista_tridimensional)

# Imprimir el array de NumPy
print(imagen_prueba)

imagen_vacia=np.zeros((1,8,8))
#print(imagen_vacia)

[[[  7  12   8  10   6   4  34  68]
  [ 21  33   5   1   6   9  77  88]
  [ 15  10   9   4  65  98  45  16]
  [ 11  19  27  29  44  37  66  52]
  [122 146 173 200 206 201 188 197]
  [101 108 100 164 222 178 210 225]
  [ 50  30  20   5 199 240 202 190]
  [ 15  25   2  10 100  45  21   2]]]


In [4]:
wav = Wavelet(imagen_prueba,3)
wav_forw = wav.forward(imagen_vacia)
print('forward \n',wav_forw)
print('\n')
wav_inv = wav.inverse(wav_forw,imagen_vacia)
print('inverse \n',wav_inv)

NameError: name 'imagen_prueba' is not defined

In [3]:
image_data_empty = ImageRaw.get_image_structure_empty()

print('original imagen \n',original_image)

wav = Wavelet(original_image,3)

matriz_wavelet = wav.forward(image_data_empty)

print('matriz forward Wavelet\n',matriz_wavelet)

matriz_recuperada = wav.inverse(matriz_wavelet,image_data_empty)

print('matriz inverse wavelet \n',matriz_recuperada)



original imagen 
 [[[16 21 25 ... 25 22 19]
  [19 25 29 ... 29 25 22]
  [22 28 34 ... 34 29 25]
  ...
  [22 28 33 ... 34 30 26]
  [19 24 29 ... 30 25 23]
  [16 21 25 ... 25 22 19]]]
(1, 128, 128)
dim: 1
fil: 128
col 128
dim: 1
fil: 64
col 64
dim: 1
fil: 32
col 32
matriz forward Wavelet
 [[[ 47.  54.  79. ...   4.   3.   3.]
  [ 52. 120. 191. ...   4.   4.   3.]
  [ 99. 216. 176. ...   5.   4.   4.]
  ...
  [  3.   5.   5. ...   3.   4.   4.]
  [  4.   4.   5. ...   3.   3.   2.]
  [  3.   4.   5. ...   3.   3.   3.]]]
matriz inverse wavelet 
 [[[16. 21. 25. ... 25. 22. 19.]
  [19. 25. 29. ... 29. 25. 22.]
  [22. 28. 34. ... 34. 29. 25.]
  ...
  [22. 28. 33. ... 34. 30. 26.]
  [19. 24. 29. ... 30. 25. 23.]
  [16. 21. 25. ... 25. 22. 19.]]]


In [4]:
'''
pred = Prediction(original_image)
imagen_prima = pred.east_pred(image_data_empty)
residu=original_image-imagen_prima
print(residu)
'''



'\npred = Prediction(original_image)\nimagen_prima = pred.east_pred(image_data_empty)\nresidu=original_image-imagen_prima\nprint(residu)\n'

In [3]:
image_data_empty = ImageRaw.get_image_structure_empty()
pred1 = Prediction(original_image)
imagen_prima1 = pred1.north_and_east(image_data_empty)
residu1 = original_image-imagen_prima1
print(residu1)
'''
pred2 = Prediction(original_image)
imagen_prima2 = pred2.north(image_data_empty)
residu2 = original_image-imagen_prima2
print(residu2)

pred3 = Prediction(original_image)
imagen_prima3 = pred3.northeast(image_data_empty)
residu3 = original_image-imagen_prima3
print(residu3)
'''

[[[ 0.  0.  0. ...  0.  0.  0.]
  [ 0.  0.  0. ...  0.  0.  0.]
  [ 0.  0. 24. ... 33. 30. 26.]
  ...
  [ 0.  0. 30. ... 42. 37. 32.]
  [ 0.  0. 27. ... 37. 33. 28.]
  [ 0.  0. 23. ... 32. 28. 25.]]]


'\npred2 = Prediction(original_image)\nimagen_prima2 = pred2.north(image_data_empty)\nresidu2 = original_image-imagen_prima2\nprint(residu2)\n\npred3 = Prediction(original_image)\nimagen_prima3 = pred3.northeast(image_data_empty)\nresidu3 = original_image-imagen_prima3\nprint(residu3)\n'

In [4]:

statistics1 = statistics(original_image)
entropy1 = statistics1.compute_entropy()
print("Entropia imagen original:", entropy1)

'''
statistics2 = statistics(matriz_wavelet)
entropy2 = statistics2.compute_entropy()
print("Entropia wavelet forward:", entropy2)

statistics3 = statistics(residu)
entropy3 = statistics3.compute_entropy()
print("Entropia predictor east (residu):", entropy3)
'''
statistics4 = statistics(residu1)
entropy4 = statistics4.compute_entropy()
print("Entropia predictor north and east (residu):", entropy4)
'''
statistics5 = statistics(residu2)
entropy5 = statistics5.compute_entropy()
print("Entropia predictor north (residu):", entropy5)

statistics6 = statistics(residu3)
entropy6 = statistics6.compute_entropy()
print("Entropia predictor northeast (residu):", entropy6)
'''

Entropia imagen original: 6.7004541529645625
Entropia predictor north and east (residu): 6.587920365229921


'\nstatistics5 = statistics(residu2)\nentropy5 = statistics5.compute_entropy()\nprint("Entropia predictor north (residu):", entropy5)\n\nstatistics6 = statistics(residu3)\nentropy6 = statistics6.compute_entropy()\nprint("Entropia predictor northeast (residu):", entropy6)\n'